const $=s=>document.querySelector(s); const api=(url,body)=>fetch(url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}).then(r=>r.json());
function card(title,value,detail,cls=''){return `<article class="card"><h3>${title}</h3><div class="metric ${cls}">${value}</div><p class="small">${detail}</p></article>`}
function signalChart(readings){let valid=readings.filter(x=>x.conductivity!==null), max=Math.max(...valid.map(x=>x.conductivity),1), points=valid.map((x,i)=>`${(i/(valid.length-1)*280).toFixed(1)},${(74-x.conductivity/max*58).toFixed(1)}`).join(' ');return `<article class="card chart-card"><h3>Conductivity signal</h3><svg viewBox="0 0 280 86" role="img" aria-label="Synthetic conductivity signal across cleaning cycle"><path d="M0 74H280 M0 16H280" stroke="#dfe7e2"/><polyline points="${points}" fill="none" stroke="#2f8956" stroke-width="3"/></svg><p class="small">Synthetic visualisation; signal is not proof of cleanliness.</p></article>`}
async function optimize(seed=2030){let d=await api('/api/optimize',{water_weight:+$('#water').value,seed});if(d.status!=='FEASIBLE'){ $('#optimizer').innerHTML=card('Planning status',d.status,d.constraint_explanation,'danger');return }let b=d.baseline.water_demand_l,o=d.optimized.water_demand_l;$('#optimizer').innerHTML=card('Baseline water demand',`${b} L`,`Synthetic queue · seed ${seed}`)+card('Recommended demand',`${o} L`,d.baseline_retained?'Baseline retained: heuristic could not improve the configured objective.':`Modeled reduction: ${(b-o).toFixed(1)} L`,'positive')+`<article class="card"><h3>Recommended sequence</h3><p class="order">${d.optimized.order.join(' → ')}</p><p class="small">${d.method}</p></article>`+`<article class="card"><h3>Decision trace</h3><p class="small">${d.optimized.transitions.slice(0,3).map(x=>x.from+'→'+x.to+': '+x.reasons.join(', ')).join('<br>')}</p></article>`+`<article class="card"><h3>Planner response</h3><button onclick="recordDecision('${d.optimization_id}','accept_recommendation')">Record advisory acceptance</button><button class="secondary" onclick="recordDecision('${d.optimization_id}','retain_baseline')">Keep baseline</button><p id="decisionStatus" class="small">No plant schedule is changed. This records a synthetic demo audit event.</p></article>`}
function exploreScenario(){optimize(3000+Math.floor(Math.random()*900000))}
async function recordDecision(optimization_id,decision){let d=await api('/api/optimization/decision',{optimization_id,decision});$('#decisionStatus').textContent=d.notice}
async function runCleaning(failure){let d=await api('/api/cleaning/start',{failure});let c=d.confidence;$('#cleaning').innerHTML=card('Model signal',d.safety_gate.model_message,'Automatic release: prohibited',c==='INSUFFICIENT DATA'?'danger':'positive')+card('Predicted endpoint',d.predicted_endpoint_minute===null?'—':d.predicted_endpoint_minute+' min',`Baseline: ${d.baseline_minutes} min · probability ${d.endpoint_probability??'—'}`)+card('Sensor status',c,`${d.readings.length} synthetic readings`,c==='INSUFFICIENT DATA'?'danger':'')+signalChart(d.readings)+`<article class="card"><h3>Latest readings</h3><p class="small">${d.readings.slice(-4).map(x=>`${x.minute}m · cond ${x.conductivity??'—'} · turb ${x.turbidity??'—'} · ${x.quality}`).join('<br>')}</p></article>`}
async function waterScreen(){let d=await api('/api/water/analyze',{volume_l:42,quality:'screened'});$('#cascadeResult').innerHTML=card('Available recovery stream',d.available_volume_l+' L','Illustrative stream')+card('Screening result',d.screening,'No reuse is approved by this prototype','positive')+`<article class="card"><h3>Required checks</h3><p class="small">${d.required_checks.join('<br>')}</p></article>`}
async function calculateImpact(){let d=await api('/api/impact/calculate',{});$('#impactResult').innerHTML=card('Common baseline',d.common_baseline_l+' L','One synthetic baseline')+card('Prevent, incremental',d.prevent_incremental_l+' L','Reduction from sequence only','positive')+card('Adapt, incremental',d.adapt_incremental_l+' L','Incremental after Prevent','positive')+card('Cascade potential',d.cascade_potential_l+' L',d.accounting_note)}
async function showPilot(){let d=await api('/api/pilot');$('#pilotResult').innerHTML=card('Pilot mode','Advisory only',d.mode)+card('Pilot scope','One line',d.scope)+`<article class="card"><h3>Stop conditions</h3><p class="small">${d.stop_conditions.join('<br>')}</p></article>`}
function resetDemo(){['#optimizer','#cleaning','#cascadeResult','#impactResult'].forEach(x=>$(x).innerHTML='');$('#water').value=1;window.scrollTo({top:0,behavior:'smooth'})} optimize(); runCleaning(); waterScreen(); calculateImpact(); showPilot();
